### PR TITLE
Added persistent storage for config.json file

### PR DESCRIPTION
**Pull request by Goobaroo**
Missing the persistent storage for the config.json.  This allows for the owners config to be added to the config.json

The backup.sh talks about copying back the config.json to persistent storage, but that storage is not defined.

### CODE REVIEW

**Comment by lnxd** [comment]
Thanks for the PR! I use that persistent storage feature for testing but if you think it might be helpful for users to have access to it, I'm happy to add it to the template.

**Comment by Goobaroo** [comment]
Yeah, it means that other config lines can be added without you having to update them.  Also provides persistence if the docker is removed for some reason and re-installed.

There is an owner filter that allows you to specify which ownership items get backed up.  For instance, I don't need my unraid server backing up all of my organizational repositories.

**Comment by lnxd** [comment]
Brilliant! When I get a chance I'll come have a look at the Unraid forums, this tiny side project of mine from what feels like forever ago has been getting a surprising amount of attention over the past little while 🤔

**Comment by Goobaroo** [comment]
You're getting more attention because your container was highlighted by the Unraid staff for Feb 2022.  Congratulations 🍾

**Pull request merged**
